name: "Publish Recanvas"
on:
  push:
    branches:
      - main

env:
  INPUT_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Setup NPM TOKEN
        run: echo "//registry.npmjs.org/:_authToken=$INPUT_TOKEN" > ~/.npmrc

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish to NPM
        run: node scripts/publish.js
